-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 17:40:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_perpusSebisaku
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_perpusSebisaku
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_perpusSebisaku` DEFAULT CHARACTER SET utf8 ;
USE `db_perpusSebisaku` ;

-- -----------------------------------------------------
-- Table `db_perpusSebisaku`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpusSebisaku`.`user` (
  `id_user` CHAR(10) NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` CHAR(100) NULL,
  `nama_lengkap` VARCHAR(45) NULL,
  `npm` VARCHAR(45) NULL,
  `alamat` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perpusSebisaku`.`kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpusSebisaku`.`kategori` (
  `id_kategori` CHAR(10) NOT NULL,
  `kategori` VARCHAR(45) NULL,
  PRIMARY KEY (`id_kategori`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perpusSebisaku`.`buku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpusSebisaku`.`buku` (
  `id_buku` CHAR(10) NOT NULL,
  `judul` VARCHAR(45) NULL,
  `penulis` VARCHAR(45) NULL,
  `penerbit` VARCHAR(45) NULL,
  `id_kategori` CHAR(10) NOT NULL,
  PRIMARY KEY (`id_buku`),
  INDEX `fk_buku_kategori1_idx` (`id_kategori` ASC) VISIBLE,
  CONSTRAINT `fk_buku_kategori1`
    FOREIGN KEY (`id_kategori`)
    REFERENCES `db_perpusSebisaku`.`kategori` (`id_kategori`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perpusSebisaku`.`peminjaman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpusSebisaku`.`peminjaman` (
  `id_peminjaman` CHAR(10) NOT NULL,
  `tanggal_pinjam` DATE NULL,
  `tanggal_kembali` DATE NULL,
  `status` ENUM('Dipinjam', 'Dikembalikan') NULL,
  `id_user` CHAR(10) NOT NULL,
  `id_buku` CHAR(10) NOT NULL,
  PRIMARY KEY (`id_peminjaman`),
  INDEX `fk_peminjaman_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_peminjaman_buku1_idx` (`id_buku` ASC) VISIBLE,
  CONSTRAINT `fk_peminjaman_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_perpusSebisaku`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peminjaman_buku1`
    FOREIGN KEY (`id_buku`)
    REFERENCES `db_perpusSebisaku`.`buku` (`id_buku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_perpusSebisaku`.`ulasan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_perpusSebisaku`.`ulasan` (
  `id_ulasan` CHAR(10) NOT NULL,
  `ulasan` VARCHAR(45) NULL,
  `rating` INT NULL,
  `id_buku` CHAR(10) NOT NULL,
  `id_user` CHAR(10) NOT NULL,
  PRIMARY KEY (`id_ulasan`),
  INDEX `fk_ulasan_buku1_idx` (`id_buku` ASC) VISIBLE,
  INDEX `fk_ulasan_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_ulasan_buku1`
    FOREIGN KEY (`id_buku`)
    REFERENCES `db_perpusSebisaku`.`buku` (`id_buku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ulasan_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_perpusSebisaku`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
