/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainAdmin;
import DatabaseConnection.DatabaseConnection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MenuUtamaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName());

    /**
     * Creates new form MenuUtamaAdmin
     */
    public MenuUtamaAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        loadDashboardData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();
        lbl_home = new javax.swing.JLabel();
        lbl_kategori = new javax.swing.JLabel();
        lbl_tambah = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnl_dataBuku = new RoundedPanel(13);
        jLabel13 = new javax.swing.JLabel();
        lbl_jumlahBuku = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pnl_anggota = new RoundedPanel(13);
        jLabel16 = new javax.swing.JLabel();
        lbl_jumlahAnggota = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabelRiwayatPeminjaman1 = new MainAdmin.TabelRiwayatPeminjaman();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_menu.setBackground(new java.awt.Color(70, 90, 215));

        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home1.png"))); // NOI18N

        lbl_kategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Kotak1.png"))); // NOI18N
        lbl_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_kategoriMouseClicked(evt);
            }
        });

        lbl_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tambah.png"))); // NOI18N
        lbl_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_tambahMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tambah)
                    .addComponent(lbl_kategori)
                    .addComponent(lbl_home))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lbl_home)
                .addGap(59, 59, 59)
                .addComponent(lbl_tambah)
                .addGap(58, 58, 58)
                .addComponent(lbl_kategori)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_menu, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel3.setText("Selamat Datang, Admin");

        pnl_dataBuku.setBackground(new java.awt.Color(70, 90, 215));
        pnl_dataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_dataBukuMouseClicked(evt);
            }
        });
        pnl_dataBuku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DATA BUKU");
        pnl_dataBuku.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        lbl_jumlahBuku.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        lbl_jumlahBuku.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jumlahBuku.setText("22");
        pnl_dataBuku.add(lbl_jumlahBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jLabel15.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Lihat Detail >");
        pnl_dataBuku.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bxs_book.png"))); // NOI18N
        pnl_dataBuku.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 22, -1, -1));

        pnl_anggota.setBackground(new java.awt.Color(106, 70, 215));
        pnl_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_anggotaMouseClicked(evt);
            }
        });
        pnl_anggota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ANGGOTA");
        pnl_anggota.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        lbl_jumlahAnggota.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        lbl_jumlahAnggota.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jumlahAnggota.setText("12");
        pnl_anggota.add(lbl_jumlahAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jLabel18.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Lihat Detail >");
        pnl_anggota.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Anggota.png"))); // NOI18N
        pnl_anggota.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("Riwayat Peminjaman");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(pnl_dataBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(pnl_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2)
                        .addComponent(tabelRiwayatPeminjaman1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(11, 11, 11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl_dataBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnl_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addComponent(jLabel2)
                    .addGap(5, 5, 5)
                    .addComponent(tabelRiwayatPeminjaman1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 630));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_tambahMouseClicked
        // TODO add your handling code here:
        new TambahBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_tambahMouseClicked

    private void lbl_kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_kategoriMouseClicked
        // TODO add your handling code here:
        new Kategori().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_kategoriMouseClicked

    private void pnl_dataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_dataBukuMouseClicked
        // TODO add your handling code here:
        new DataBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnl_dataBukuMouseClicked

    private void pnl_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_anggotaMouseClicked
        // TODO add your handling code here:
        new Anggota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnl_anggotaMouseClicked

    public void loadDashboardData() {
    try {
        Connection conn = DatabaseConnection.getConnection();

        // Hitung jumlah buku
        String sqlBuku = "SELECT COUNT(*) AS total FROM buku";
        PreparedStatement psBuku = conn.prepareStatement(sqlBuku);
        ResultSet rsBuku = psBuku.executeQuery();
        if (rsBuku.next()) {
            int totalBuku = rsBuku.getInt("total");
            lbl_jumlahBuku.setText(String.valueOf(totalBuku));
        }

        // Hitung jumlah anggota
        String sqlUser = "SELECT COUNT(*) AS total FROM user";
        PreparedStatement psUser = conn.prepareStatement(sqlUser);
        ResultSet rsUser = psUser.executeQuery();
        if (rsUser.next()) {
            int totalUser = rsUser.getInt("total");
            lbl_jumlahAnggota.setText(String.valueOf(totalUser));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error memuat data dashboard: " + e.getMessage());
    }
}

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUtamaAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_jumlahAnggota;
    private javax.swing.JLabel lbl_jumlahBuku;
    private javax.swing.JLabel lbl_kategori;
    private javax.swing.JLabel lbl_tambah;
    private javax.swing.JPanel pnl_anggota;
    private javax.swing.JPanel pnl_dataBuku;
    private javax.swing.JPanel pnl_menu;
    private MainAdmin.TabelRiwayatPeminjaman tabelRiwayatPeminjaman1;
    // End of variables declaration//GEN-END:variables
}
