/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import Main.TabelDaftarBuku;
import Models.SavedBooks;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author USER
 */
public class DaftarBuku extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DaftarBuku.class.getName());

    /**
     * Creates new form DaftarBuku
     */
    public DaftarBuku() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();
        lbl_home = new javax.swing.JLabel();
        lbl_pinjam = new javax.swing.JLabel();
        lbl_kategori = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tabelDaftarBuku1 = new Main.TabelDaftarBuku();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_menu.setBackground(new java.awt.Color(70, 90, 215));

        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home1.png"))); // NOI18N
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
        });

        lbl_pinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Book1.png"))); // NOI18N
        lbl_pinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pinjamMouseClicked(evt);
            }
        });

        lbl_kategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Kotak1.png"))); // NOI18N
        lbl_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_kategoriMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_kategori)
                    .addComponent(lbl_pinjam)
                    .addComponent(lbl_home))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lbl_home)
                .addGap(59, 59, 59)
                .addComponent(lbl_pinjam)
                .addGap(53, 53, 53)
                .addComponent(lbl_kategori)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_menu, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1020, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(50, 68, 182));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DAFTAR BUKU");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addContainerGap(755, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(29, 29, 29))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));
        jPanel3.add(tabelDaftarBuku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1000, -1));

        jPanel2.setBackground(new java.awt.Color(70, 90, 215));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Simpan Buku");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 9, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 110, 35));

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_homeMouseClicked

    private void lbl_kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_kategoriMouseClicked
        // TODO add your handling code here:
        new DaftarKategori().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_kategoriMouseClicked

    private void lbl_pinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pinjamMouseClicked
        // TODO add your handling code here:
        new PinjamBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_pinjamMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        JTable table = tabelDaftarBuku1.getTable();
        int selectedRow = table.getSelectedRow();
        
        if (selectedRow != -1) {
        // Ambil data kolom-kolom
        String id = table.getValueAt(selectedRow, 0).toString();
        String judul = table.getValueAt(selectedRow, 1).toString();
        String penulis = table.getValueAt(selectedRow, 2).toString();
        String deskripsi = table.getValueAt(selectedRow, 3).toString();
        String status = table.getValueAt(selectedRow, 4).toString();

        // Simpan ke Shared List
        SavedBooks.savedList.add(new String[]{id, judul, penulis, deskripsi, status});

        JOptionPane.showMessageDialog(null, "Buku berhasil disimpan!");
    }
    else {
        JOptionPane.showMessageDialog(null, "Pilih salah satu buku dulu!");
    }
    }//GEN-LAST:event_jPanel2MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DaftarBuku().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_kategori;
    private javax.swing.JLabel lbl_pinjam;
    private javax.swing.JPanel pnl_menu;
    private Main.TabelDaftarBuku tabelDaftarBuku1;
    // End of variables declaration//GEN-END:variables
}
