/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import DAO.PeminjamanDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class KembalikanBuku extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KembalikanBuku.class.getName());

    /**
     * Creates new form KembalikanBuku
     */
    public KembalikanBuku() {
        initComponents();
        jPanel1.requestFocusInWindow();
        setLocationRelativeTo(null);
    }
    private void loadBorrowedBooks() {
    String username = txtUsername.getText().trim();

    if (username.isEmpty()) return;

    PeminjamanDAO pdao = new PeminjamanDAO();
    List<String> borrowedBooks = pdao.getBorrowedBooksByUsername(username);

    cbOpsi1.removeAllItems();

    for (String judul : borrowedBooks) {
        cbOpsi1.addItem(judul);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();
        lbl_home = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_kategori = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbOpsi12 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbOpsi1 = new javax.swing.JComboBox<>();
        pnl_kembalikan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_menu.setBackground(new java.awt.Color(70, 90, 215));

        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home2.png"))); // NOI18N
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Book2.png"))); // NOI18N

        lbl_kategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Kotak1.png"))); // NOI18N
        lbl_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_kategoriMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_kategori)
                    .addComponent(jLabel19)
                    .addComponent(lbl_home))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lbl_home)
                .addGap(59, 59, 59)
                .addComponent(jLabel19)
                .addGap(53, 53, 53)
                .addComponent(lbl_kategori)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_menu, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbOpsi12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kembalikan Buku", "Pinjam Buku" }));
        cbOpsi12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbOpsi12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbOpsi12MouseClicked(evt);
            }
        });
        cbOpsi12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpsi12ActionPerformed(evt);
            }
        });
        jPanel2.add(cbOpsi12, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 22, 226, 32));

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 90, 215));
        jLabel2.setText("Username");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel4.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 896, 33));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 90, 215));
        jLabel3.setText("Buku yang akan Dikembalkan");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        cbOpsi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(cbOpsi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 896, 32));

        pnl_kembalikan.setBackground(new java.awt.Color(70, 90, 215));
        pnl_kembalikan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_kembalikanMouseClicked(evt);
            }
        });
        pnl_kembalikan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kembalikan");
        pnl_kembalikan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 7, -1, -1));

        jPanel4.add(pnl_kembalikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 120, 34));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 25, 981, 510));

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
        loadBorrowedBooks();
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void cbOpsi12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpsi12ActionPerformed
        // TODO add your handling code here:
        String pilihan1 = (String) cbOpsi12.getSelectedItem();

        if (pilihan1.equals("Pinjam Buku")) {
        new PinjamBuku().setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_cbOpsi12ActionPerformed

    private void cbOpsi12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbOpsi12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOpsi12MouseClicked

    private void lbl_kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_kategoriMouseClicked
        // TODO add your handling code here:
        new DaftarKategori().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_kategoriMouseClicked

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_homeMouseClicked

    private void pnl_kembalikanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_kembalikanMouseClicked
        // TODO add your handling code here:
        String username = txtUsername.getText().trim();
        String judulDipilih = cbOpsi1.getSelectedItem().toString();

        if (username.isEmpty() || judulDipilih == null) {
            JOptionPane.showMessageDialog(this, 
                    "Isi Username dan pilih buku!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        PeminjamanDAO dao = new PeminjamanDAO();
        boolean sukses = dao.kembalikanBuku(username, judulDipilih);

        if (sukses) {
            JOptionPane.showMessageDialog(this, 
                    "Buku berhasil dikembalikan!", 
                    "Sukses", 
                    JOptionPane.INFORMATION_MESSAGE);

            // Refresh ComboBox agar buku yang sudah dikembalikan hilang dari daftar
            loadBorrowedBooks();

        } else {
        JOptionPane.showMessageDialog(this, 
                "Pengembalian gagal! Pastikan username dan buku valid.", 
                "Gagal", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pnl_kembalikanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KembalikanBuku().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbOpsi1;
    private javax.swing.JComboBox<String> cbOpsi12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_kategori;
    private javax.swing.JPanel pnl_kembalikan;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
