/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import DatabaseConnection.DatabaseConnection;
import Models.SavedBooks;
import java.sql.*;
import javax.swing.JOptionPane;
import project.perpustakaan.loginPage1;

/**
 *
 * @author USER
 */

public class MenuUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtama.class.getName());

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        setLocationRelativeTo(null);
        loadDashboardData();
        updateCounter();
        updateRiwayatCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        pnl_menu = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pnl_dasar = new javax.swing.JPanel();
        pnl_simpan = new RoundedPanel(13);
        jLabel12 = new javax.swing.JLabel();
        lbl_jumlahRiwayat = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pnl_pinjam1 = new RoundedPanel(13);
        lbl_jumlahBuku = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnl_aturan = new RoundedPanel(15);
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnl_simpan1 = new RoundedPanel(13);
        jLabel14 = new javax.swing.JLabel();
        lbl_jumlahSimpan1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_menu.setBackground(new java.awt.Color(70, 90, 215));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home1.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Book1.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Kotak1.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel20)
                .addGap(59, 59, 59)
                .addComponent(jLabel19)
                .addGap(53, 53, 53)
                .addComponent(jLabel22)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_menu, java.awt.BorderLayout.LINE_START);

        pnl_dasar.setBackground(new java.awt.Color(255, 255, 255));
        pnl_dasar.setPreferredSize(new java.awt.Dimension(1117, 630));
        pnl_dasar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_simpan.setBackground(new java.awt.Color(106, 70, 215));
        pnl_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_simpanMouseClicked(evt);
            }
        });
        pnl_simpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("RIWAYAT PEMINJAMANMU");
        pnl_simpan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        lbl_jumlahRiwayat.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        lbl_jumlahRiwayat.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jumlahRiwayat.setText("0");
        pnl_simpan.add(lbl_jumlahRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lihat Detail >");
        pnl_simpan.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Riwayat1.png"))); // NOI18N
        pnl_simpan.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 35, -1, -1));

        pnl_dasar.add(pnl_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 260, 110));

        pnl_pinjam1.setBackground(new java.awt.Color(70, 90, 215));
        pnl_pinjam1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_pinjam1MouseClicked(evt);
            }
        });
        pnl_pinjam1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_jumlahBuku.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        lbl_jumlahBuku.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jumlahBuku.setText("0");
        pnl_pinjam1.add(lbl_jumlahBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jLabel15.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Lihat Disini >");
        pnl_pinjam1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bxs_book.png"))); // NOI18N
        pnl_pinjam1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 22, -1, -1));

        jLabel21.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DAFTAR BUKU");
        pnl_pinjam1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        pnl_dasar.add(pnl_pinjam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 250, 110));

        pnl_aturan.setBackground(new java.awt.Color(213, 219, 239));
        pnl_aturan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel1.setText("7. Perpanjangan peminjaman dapat dilakukan maksimal 1 kali sebelum jatuh tempo.");
        pnl_aturan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel4.setText("1. Setiap anggota dapat meminjam maksimal 3 buku.");
        pnl_aturan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel5.setText("2. Peminjaman hanya dapat dilakukan oleh anggota aktif perpustakaan yang telah terdaftar.");
        pnl_aturan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel6.setText("3. Lama peminjaman adalah 7 hari.");
        pnl_aturan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel7.setText("4. Buku yang terlambat dikembalikan akan dikenai denda Rp500 per hari.");
        pnl_aturan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel8.setText("5. Buku harus dijaga dalam kondisi baik dan tidak rusak.");
        pnl_aturan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel9.setText("6. Buku yang rusak atau hilang menjadi tanggung jawab peminjam dan wajib diganti dengan buku yang sama atau sejenis");
        pnl_aturan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel10.setText("Aturan Peminjaman");
        pnl_aturan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pnl_dasar.add(pnl_aturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 850, 220));

        lbl_user.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lbl_user.setText("User");
        pnl_dasar.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel13.setText("Selamat Datang,");
        pnl_dasar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        pnl_simpan1.setBackground(new java.awt.Color(106, 70, 215));
        pnl_simpan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_simpan1MouseClicked(evt);
            }
        });
        pnl_simpan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SIMPAN BUKUMU");
        pnl_simpan1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        lbl_jumlahSimpan1.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        lbl_jumlahSimpan1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jumlahSimpan1.setText("0");
        pnl_simpan1.add(lbl_jumlahSimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jLabel16.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Lihat Detail >");
        pnl_simpan1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/material-symbols_bookmark.png"))); // NOI18N
        pnl_simpan1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 22, -1, -1));

        pnl_dasar.add(pnl_simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 260, 110));

        getContentPane().add(pnl_dasar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_pinjam1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_pinjam1MouseClicked
        // TODO add your handling code here:
        new DaftarBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnl_pinjam1MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        new PinjamBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        new DaftarKategori().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void pnl_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_simpanMouseClicked
        // TODO add your handling code here:
        new RiwayatPeminjaman().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnl_simpanMouseClicked

    private void pnl_simpan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_simpan1MouseClicked
        // TODO add your handling code here:
        new SimpanBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnl_simpan1MouseClicked

    public void loadDashboardData() {
    try {
        Connection conn = DatabaseConnection.getConnection();

        // Hitung jumlah buku
        String sqlBuku = "SELECT COUNT(*) AS total FROM buku";
        PreparedStatement psBuku = conn.prepareStatement(sqlBuku);
        ResultSet rsBuku = psBuku.executeQuery();
        if (rsBuku.next()) {
            int totalBuku = rsBuku.getInt("total");
            lbl_jumlahBuku.setText(String.valueOf(totalBuku));
        }
        
        //Hitung jumlah buku tersimpan
        lbl_jumlahSimpan1.setText(String.valueOf(SavedBooks.savedList.size()));
        
        


    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error memuat data dashboard: " + e.getMessage());
    }
}
    
    private void updateCounter() {
    lbl_jumlahSimpan1.setText(String.valueOf(SavedBooks.savedList.size()));
}
    private int getJumlahRiwayat() {
    int jumlah = 0;

    try {
        Connection conn = DatabaseConnection.getConnection();
        
        String sql = "SELECT COUNT(*) AS total FROM peminjaman WHERE user_id = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, Session.userId);

        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            jumlah = rs.getInt("total");
        }

    } catch (SQLException e) {
        System.out.println("Error hitung riwayat: " + e.getMessage());
    }

    return jumlah;
}
    
    private void updateRiwayatCount() {
    int count = getJumlahRiwayat();
    lbl_jumlahRiwayat.setText(String.valueOf(count));
}

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_jumlahBuku;
    private javax.swing.JLabel lbl_jumlahRiwayat;
    private javax.swing.JLabel lbl_jumlahSimpan1;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel pnl_aturan;
    private javax.swing.JPanel pnl_dasar;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_pinjam1;
    private javax.swing.JPanel pnl_simpan;
    private javax.swing.JPanel pnl_simpan1;
    // End of variables declaration//GEN-END:variables
}
