/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import javax.swing.UIManager;
import DAO.BookDAO;
import java.util.List;
import Models.User;
import DAO.UserDAO;
import javax.swing.JOptionPane;
import DatabaseConnection.DatabaseConnection;
import java.sql.*;
import DAO.PeminjamanDAO;

/**
 *
 * @author USER
 */
public class PinjamBuku extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PinjamBuku.class.getName());

    /**
     * Creates new form PinjamBuku
     */
    public PinjamBuku() {
        initComponents();
        jPanel1.requestFocusInWindow();
        setLocationRelativeTo(null);
        loadAvailableBooks();
    }
    
    private void loadAvailableBooks() {
    BookDAO dao = new BookDAO();
    List<String> titles = dao.getAvailableBookTitles();

    cbOpsi1.removeAllItems(); 
    for (String title : titles) {
        cbOpsi1.addItem(title);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();
        lbl_home = new javax.swing.JLabel();
        lbl_pinjam = new javax.swing.JLabel();
        lbl_kategori = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbOpsi = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        cbOpsi1 = new javax.swing.JComboBox<>();
        pnl_submit = new RoundedPanel(13);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_menu.setBackground(new java.awt.Color(70, 90, 215));

        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home2.png"))); // NOI18N
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
        });

        lbl_pinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Book2.png"))); // NOI18N

        lbl_kategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Kotak1.png"))); // NOI18N
        lbl_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_kategoriMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_kategori)
                    .addComponent(lbl_pinjam)
                    .addComponent(lbl_home))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lbl_home)
                .addGap(59, 59, 59)
                .addComponent(lbl_pinjam)
                .addGap(53, 53, 53)
                .addComponent(lbl_kategori)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_menu, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbOpsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pinjam Buku", "Kembalikan Buku" }));
        cbOpsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbOpsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpsiActionPerformed(evt);
            }
        });
        jPanel2.add(cbOpsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 22, 226, 32));

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(1020, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 90, 215));
        jLabel2.setText("Username");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel4.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 896, 33));

        cbOpsi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbOpsi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpsi1ActionPerformed(evt);
            }
        });
        jPanel4.add(cbOpsi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 896, 32));

        pnl_submit.setBackground(new java.awt.Color(70, 90, 215));
        pnl_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_submitMouseClicked(evt);
            }
        });
        pnl_submit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Submit");
        pnl_submit.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 7, -1, -1));

        jPanel4.add(pnl_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 99, 34));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 90, 215));
        jLabel5.setText("Buku yang Dipinjam");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 25, 981, 500));

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void cbOpsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpsiActionPerformed
        // TODO add your handling code here:
        String pilihan = (String) cbOpsi.getSelectedItem();

        if (pilihan.equals("Kembalikan Buku")) {
        new KembalikanBuku().setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_cbOpsiActionPerformed

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_homeMouseClicked

    private void lbl_kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_kategoriMouseClicked
        // TODO add your handling code here:
        new DaftarKategori().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_kategoriMouseClicked

    private void cbOpsi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpsi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOpsi1ActionPerformed

    private void pnl_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_submitMouseClicked
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String judulBuku = cbOpsi1.getSelectedItem().toString();

        PeminjamanDAO dao = new PeminjamanDAO();

        boolean sukses = dao.pinjamBuku(username, judulBuku);

        if (sukses) {
            JOptionPane.showMessageDialog(this,
                "Buku berhasil dipinjam!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                "Pinjam buku gagal!\nPastikan username valid dan buku tersedia.",
                "Gagal",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pnl_submitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PinjamBuku().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbOpsi;
    private javax.swing.JComboBox<String> cbOpsi1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_kategori;
    private javax.swing.JLabel lbl_pinjam;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_submit;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
