/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.perpustakaan;
import Main.MenuUtama;
import MainAdmin.MenuUtamaAdmin;
import javax.swing.JOptionPane;
import DAO.UserDAO;
import Models.User;
import DatabaseConnection.DatabaseConnection;
import Main.Session;


/**
 *
 * @author USER
 */


public class loginPage1 extends javax.swing.JFrame {
    
    public static String currentUsername;
    int xx, xy;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginPage1.class.getName());

    /**
     * Creates new form loginPage1
     */
    public loginPage1() {
        initComponents();
        jPanel1.requestFocusInWindow();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new RoundedPanel(20);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername1 = txtUsername1 = new RoundedPlaceholderTextField("   Username");
        lbl_daftar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnMasuk = new RoundedPanel(20);
        jLabel8 = new javax.swing.JLabel();
        txtPassword = txtPassword = new RoundedPlaceholderPasswordField("   Password")
        ;
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(50, 68, 182));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setText("Temukan Bukumu");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 9)); // NOI18N
        jLabel3.setText("Masuk untuk melanjutkan membaca dan belajar lebih dalam");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 52, -1, -1));

        txtUsername1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtUsername1.setForeground(new java.awt.Color(116, 134, 196));
        txtUsername1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 68, 182), 2));
        txtUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 33));

        lbl_daftar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lbl_daftar.setForeground(new java.awt.Color(70, 90, 215));
        lbl_daftar.setText("Daftar Disini!");
        lbl_daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_daftarMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 275, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Belum punya akun?");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 275, -1, -1));

        btnMasuk.setBackground(new java.awt.Color(70, 90, 215));
        btnMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasukMouseClicked(evt);
            }
        });
        btnMasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Masuk");
        btnMasuk.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 11, 40, -1));

        jPanel2.add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 260, 40));

        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 68, 182), 2));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 132, 260, 35));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 320, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO 2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void txtUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername1ActionPerformed

    private void lbl_daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_daftarMouseClicked
        // TODO add your handling code here:
        new registPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_daftarMouseClicked

    private void btnMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukMouseClicked
        String username = txtUsername1.getText();
        String password = new String(txtPassword.getPassword());

        // 1. CEK AKUN ADMIN
        if (username.equals("admin") && password.equals("admin123321")) {
            JOptionPane.showMessageDialog(this, "Login Admin Berhasil!");
            new MenuUtamaAdmin().setVisible(true); // Form admin
            this.dispose();
            return;
        }
    
        // 2. CEK AKUN USER
        UserDAO dao = new UserDAO();
        User user = dao.login(username, password);
        
        if(user != null) {
            Session.setUserId(user.getUserid());

            JOptionPane.showMessageDialog(this, "Login berhasil sebagai User");
            currentUsername = txtUsername1.getText();
            new MenuUtama().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Username atau Password Salah!");
        }
        
        
    }//GEN-LAST:event_btnMasukMouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loginPage1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_daftar;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
