/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.perpustakaan;
import DatabaseConnection.DatabaseConnection;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author USER
 */
public class registPage extends javax.swing.JFrame {
    
    int xx, xy;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registPage.class.getName());

    /**
     * Creates new form registPage
     */
    public registPage() {
        initComponents();
        jPanel1.requestFocusInWindow();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new RoundedPanel(20);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNoTelp = txtNoTelp = new RoundedPlaceholderTextField("   No.Telp");
        ;
        btnDaftar = new RoundedPanel(20);
        jLabel7 = new javax.swing.JLabel();
        lbl_masuk = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNpm = txtNpm = new RoundedPlaceholderTextField("   Npm");
        txtEmail = txtEmail = new RoundedPlaceholderTextField("   Email");
        ;
        txtNamaLengkap = txtNamaLengkap = new RoundedPlaceholderTextField("   Nama Lengkap");
        txtPassword = txtPassword = new RoundedPlaceholderTextField("   Password");
        txtAlamat = txtAlamat = new RoundedPlaceholderTextField("   Alamat");
        txtUsername = txtUsername = new RoundedPlaceholderTextField("   Username");
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(50, 68, 182));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setText("Buat Akunmu Sekarang");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 9)); // NOI18N
        jLabel3.setText("Simpan buku favoritmu dan temukan referensi terbaik setiap hari.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, -1, -1));

        txtNoTelp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtNoTelp.setForeground(new java.awt.Color(116, 134, 196));
        txtNoTelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 68, 182), 2));
        txtNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelpActionPerformed(evt);
            }
        });
        jPanel2.add(txtNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, 33));

        btnDaftar.setBackground(new java.awt.Color(70, 90, 215));
        btnDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarMouseClicked(evt);
            }
        });
        btnDaftar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Daftar");
        btnDaftar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 6, 40, -1));

        jPanel2.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 270, 30));

        lbl_masuk.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lbl_masuk.setForeground(new java.awt.Color(70, 90, 215));
        lbl_masuk.setText("Masuk Disini!");
        lbl_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_masukMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 281, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Sudah punya akun?");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 281, -1, -1));

        txtNpm.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtNpm.setForeground(new java.awt.Color(116, 134, 196));
        txtNpm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 68, 182), 2));
        txtNpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNpmActionPerformed(evt);
            }
        });
        jPanel2.add(txtNpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, 33));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(116, 134, 196));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 68, 182), 2));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 33));

        txtNamaLengkap.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtNamaLengkap.setForeground(new java.awt.Color(116, 134, 196));
        txtNamaLengkap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 68, 182), 2));
        txtNamaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaLengkapActionPerformed(evt);
            }
        });
        jPanel2.add(txtNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 33));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(116, 134, 196));
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 68, 182), 2));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 270, 30));

        txtAlamat.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(116, 134, 196));
        txtAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 68, 182), 2));
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        jPanel2.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 270, 30));

        txtUsername.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(116, 134, 196));
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 68, 182), 2));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, 270, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 320, 305));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO 2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpActionPerformed

    private void txtNpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNpmActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNamaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaLengkapActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void lbl_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_masukMouseClicked
        // TODO add your handling code here:
        new loginPage1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_masukMouseClicked

    private void btnDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarMouseClicked
        // TODO add your handling code here:
        String email = txtEmail.getText().trim();
        String noTelp = txtNoTelp.getText().trim();
        String namaLengkap = txtNamaLengkap.getText().trim();
        String npm = txtNpm.getText().trim();
        String alamat = txtAlamat.getText().trim();
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim();
        
        if(email.isEmpty() || noTelp.isEmpty() || namaLengkap.isEmpty() || npm.isEmpty() || alamat.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi Form Pendaftaran dengan Lengkap", "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
        Connection conn = DatabaseConnection.getConnection();

        String sql = "INSERT INTO user (username, password, email, nama_lengkap, npm, alamat, no_telp) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, username);
        pst.setString(2, password);
        pst.setString(3, email);
        pst.setString(4, namaLengkap);
        pst.setString(5, npm);
        pst.setString(6, alamat);
        pst.setString(7, noTelp);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Pendaftaran berhasil!");
        new loginPage1().setVisible(true);
        this.dispose();

        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDaftarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new registPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnDaftar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_masuk;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNamaLengkap;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JTextField txtNpm;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
